# This file is a template, and might need editing before it works on your project. 
# PHP example: http://docs.gitlab.com/ce/ci/examples/php.html
image: balintsera/php56-node-gl-runner

# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is commited to
# your git repository.
cache:
  paths:
  - vendor/
  - wordpress/
  - uploads/

before_script:
- bash ci/docker_install.sh > /dev/null
# Composer install
- composer install


php_standards:
  type: test
  script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  allow_failure: true

javascript_standards:
  type: test
  script:
  - npm install
  - node_modules/eslint/bin/eslint.js -c .eslint src/themes/pass/js/functions.js
  allow_failure: true

staging:
  type: deploy
  only:
  - master
  script:
  - curl -k -uuser:pass http://example.com/deploy.php

